version: "3"
services:
    db:
      image: mysql:latest
      container_name: std02-mysql
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: std02
      volumes:
        - std02-volumes:/var/lib/mysql  
      ports:
        - "3307:3306"  
      networks:
        - my_network    

    phpmyadmin: 
      image: phpmyadmin:latest
      container_name: std02-phpmyadmin
      environment:
        PMA_HOST: db
        PMA_PORT: 3306
        PMA_USER: root
        PMA_PASSWORD: password
      ports:
        - '8080:80' 
      depends_on:
        - db   
      networks:
        - my_network  

    redis:
      image: redis:latest
      container_name: std02-redis
      ports:
        - '6379:6379'
      networks:
        - my_network  

networks:
  my_network:
    driver: bridge

volumes:
  std02-volumes:
    driver: local
      



